package com.suhov.aaspc2023.domain.models

import com.google.gson.annotations.SerializedName

data class GitHubUserItem(
	@SerializedName("tags_url") val tagsUrl: String? = null,
	@SerializedName("private") val jsonMemberPrivate: Boolean? = null,
	@SerializedName("contributors_url") val contributorsUrl: String? = null,
	@SerializedName("notifications_url") val notificationsUrl: String? = null,
	@SerializedName("description") val description: String? = null,
	@SerializedName("subscription_url") val subscriptionUrl: String? = null,
	@SerializedName("keys_url") val keysUrl: String? = null,
	@SerializedName("branches_url") val branchesUrl: String? = null,
	@SerializedName("deployments_url") val deploymentsUrl: String? = null,
	@SerializedName("issue_comment_url") val issueCommentUrl: String? = null,
	@SerializedName("labels_url") val labelsUrl: String? = null,
	@SerializedName("subscribers_url") val subscribersUrl: String? = null,
	@SerializedName("releases_url") val releasesUrl: String? = null,
	@SerializedName("comments_url") val commentsUrl: String? = null,
	@SerializedName("stargazers_url") val stargazersUrl: String? = null,
	@SerializedName("id") val id: Int? = null,
	@SerializedName("owner") val owner: GitHubOwner? = null,
	@SerializedName("archive_url") val archiveUrl: String? = null,
	@SerializedName("commits_url") val commitsUrl: String? = null,
	@SerializedName("git_refs_url") val gitRefsUrl: String? = null,
	@SerializedName("forks_url") val forksUrl: String? = null,
	@SerializedName("compare_url") val compareUrl: String? = null,
	@SerializedName("statuses_url") val statusesUrl: String? = null,
	@SerializedName("git_commits_url") val gitCommitsUrl: String? = null,
	@SerializedName("blobs_url") val blobsUrl: String? = null,
	@SerializedName("git_tags_url") val gitTagsUrl: String? = null,
	@SerializedName("merges_url") val mergesUrl: String? = null,
	@SerializedName("downloads_url") val downloadsUrl: String? = null,
	@SerializedName("url") val url: String? = null,
	@SerializedName("contents_url") val contentsUrl: String? = null,
	@SerializedName("milestones_url") val milestonesUrl: String? = null,
	@SerializedName("teams_url") val teamsUrl: String? = null,
	@SerializedName("fork") val fork: Boolean? = null,
	@SerializedName("issues_url") val issuesUrl: String? = null,
	@SerializedName("full_name") val fullName: String? = null,
	@SerializedName("events_url") val eventsUrl: String? = null,
	@SerializedName("issue_events_url") val issueEventsUrl: String? = null,
	@SerializedName("languages_url") val languagesUrl: String? = null,
	@SerializedName("html_url") val htmlUrl: String? = null,
	@SerializedName("collaborators_url") val collaboratorsUrl: String? = null,
	@SerializedName("name") val name: String? = null,
	@SerializedName("pulls_url") val pullsUrl: String? = null,
	@SerializedName("hooks_url") val hooksUrl: String? = null,
	@SerializedName("assignees_url") val assigneesUrl: String? = null,
	@SerializedName("trees_url") val treesUrl: String? = null,
	@SerializedName("node_id") val nodeId: String? = null
)

data class GitHubOwner(
	@SerializedName("gists_url") val gistsUrl: String? = null,
	@SerializedName("repos_url") val reposUrl: String? = null,
	@SerializedName("following_url") val followingUrl: String? = null,
	@SerializedName("starred_url") val starredUrl: String? = null,
	@SerializedName("login") val login: String? = null,
	@SerializedName("followers_url") val followersUrl: String? = null,
	@SerializedName("type") val type: String? = null,
	@SerializedName("url") val url: String? = null,
	@SerializedName("subscriptions_url") val subscriptionsUrl: String? = null,
	@SerializedName("received_events_url") val receivedEventsUrl: String? = null,
	@SerializedName("avatar_url") val avatarUrl: String? = null,
	@SerializedName("events_url") val eventsUrl: String? = null,
	@SerializedName("html_url") val htmlUrl: String? = null,
	@SerializedName("site_admin") val siteAdmin: Boolean? = null,
	@SerializedName("id") val id: Int? = null,
	@SerializedName("gravatar_id") val gravatarId: String? = null,
	@SerializedName("node_id") val nodeId: String? = null,
	@SerializedName("organizations_url") val organizationsUrl: String? = null
)
